# Generated by Django 5.0.1 on 2024-02-06 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# extensionapis.migrations.0008_auto_20240205_0331

class Migration(migrations.Migration):

    replaces = [('extensionapis', '0001_initial'), ('extensionapis', '0002_rawdoccapture_parseddoccapture'), ('extensionapis', '0003_rawdoccapture_title_rawdoccapture_url'), ('extensionapis', '0004_singleurl_observedlink_rawdoccapture_url_model_and_more'), ('extensionapis', '0005_delete_authtokens'), ('extensionapis', '0006_rawdoccapture_reader_location_container_and_more'), ('extensionapis', '0007_rawdoccapture_guid'), ('extensionapis', '0008_auto_20240205_0331'), ('extensionapis', '0009_auto_20240205_0331'), ('extensionapis', '0010_rawdoccapture_capture_index'), ('extensionapis', '0011_remove_rawdoccapture_id_alter_rawdoccapture_guid')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('url', models.CharField(max_length=2048)),
                ('host', models.CharField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'url')},
            },
        ),
        migrations.CreateModel(
            name='ObservedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('from_str', models.CharField(max_length=2028)),
                ('to_str', models.CharField(max_length=2048)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('from_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to='extensionapis.singleurl')),
                ('to_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target', to='extensionapis.singleurl')),
            ],
            options={
                'unique_together': {('user', 'from_str', 'to_str')},
            },
        ),
        migrations.CreateModel(
            name='SingleUrlFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('fact_key', models.CharField(max_length=64)),
                ('fact_value', models.CharField(max_length=512)),
                ('base_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensionapis.singleurl')),
            ],
            options={
                'unique_together': {('base_url', 'fact_key')},
            },
        ),
        migrations.CreateModel(
            name='RawDocCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('location_container', models.CharField(max_length=64)),
                ('location_path', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(default='', max_length=1024)),
                ('url', models.CharField(default='', max_length=2048)),
                ('url_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='extensionapis.singleurl')),
                ('reader_location_container', models.CharField(default='', max_length=64)),
                ('reader_location_path', models.CharField(default='', max_length=256)),
                ('guid', models.UUIDField(default=uuid.uuid4, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rawdoccapture',
            name='capture_index',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='rawdoccapture',
            name='id',
        ),
        migrations.AlterField(
            model_name='rawdoccapture',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
