# Generated by Django 5.0.2 on 2024-02-17 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extensionapis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='observedlink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawdoccapture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='singleurl',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawdoccapture',
            name='url_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='extensionapis.singleurl'),
        ),
        migrations.AddField(
            model_name='observedlink',
            name='from_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to='extensionapis.singleurl'),
        ),
        migrations.AddField(
            model_name='observedlink',
            name='to_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target', to='extensionapis.singleurl'),
        ),
        migrations.AddField(
            model_name='singleurlfact',
            name='base_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensionapis.singleurl'),
        ),
        migrations.AlterUniqueTogether(
            name='singleurl',
            unique_together={('user', 'url')},
        ),
        migrations.AlterUniqueTogether(
            name='observedlink',
            unique_together={('user', 'from_str', 'to_str')},
        ),
        migrations.AlterUniqueTogether(
            name='singleurlfact',
            unique_together={('base_url', 'fact_key')},
        ),
    ]
