# Generated by Django 5.0.2 on 2024-03-12 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extensionapis", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rawdoccapture",
            options={"get_latest_by": "date_modified"},
        ),
    ]
