# Generated by Django 5.0 on 2023-12-09 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extensionapis", "0003_rawdoccapture_title_rawdoccapture_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SingleUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("url", models.CharField(max_length=2048)),
                ("host", models.CharField(max_length=512)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "url")},
            },
        ),
        migrations.CreateModel(
            name="ObservedLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("from_str", models.CharField(max_length=2028)),
                ("to_str", models.CharField(max_length=2048)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_obj",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source",
                        to="extensionapis.singleurl",
                    ),
                ),
                (
                    "to_obj",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target",
                        to="extensionapis.singleurl",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "from_str", "to_str")},
            },
        ),
        migrations.AddField(
            model_name="rawdoccapture",
            name="url_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="extensionapis.singleurl",
            ),
        ),
        migrations.CreateModel(
            name="SingleUrlFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("fact_key", models.CharField(max_length=64)),
                ("fact_value", models.CharField(max_length=512)),
                (
                    "base_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="extensionapis.singleurl",
                    ),
                ),
            ],
            options={
                "unique_together": {("base_url", "fact_key")},
            },
        ),
        migrations.DeleteModel(
            name="ParsedDocCapture",
        ),
    ]
