# Generated by Django 5.0.1 on 2024-02-05 03:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensionapis', '0006_rawdoccapture_reader_location_container_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdoccapture',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
