# Generated by Django 5.0.1 on 2024-02-05 03:31
from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("extensionapis", "RawDocCapture")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["guid"])


class Migration(migrations.Migration):
    dependencies = [
        ('extensionapis', '0007_rawdoccapture_guid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid),
    ]
