# Generated by Django 5.0.1 on 2024-02-05 03:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensionapis', '0010_rawdoccapture_capture_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdoccapture',
            name='id',
        ),
        migrations.AlterField(
            model_name='rawdoccapture',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
