# Generated by Django 5.0.1 on 2024-02-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensionapis', '0001_squashed_0011_remove_rawdoccapture_id_alter_rawdoccapture_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdoccapture',
            name='capture_index',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rawdoccapture',
            name='reader_location_container',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='rawdoccapture',
            name='reader_location_path',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='rawdoccapture',
            name='title',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='rawdoccapture',
            name='url',
            field=models.CharField(max_length=2048),
        ),
    ]
