repos:
#  - repo: pycqa/pylint
#    revision: 'main'
#    hooks:
#      - id: pylint
#        name: Pylint
#        language: python
#
#  - repo: pycodestyle/pycodestyle
#    revision: 'main'
#    hooks:
#      - id: pycodestyle
#        name: Pycodestyle

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format