version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "5678:5678"
    volumes:
      - "./:/app"
    command: sh -c "poetry run python"
  worker:
    build:
      context: ./
      dockerfile: Dockerfile
#    image: flexindex.azurecr.io/worker
    working_dir: /app/webserve
    command: poetry run python manage.py rqworker
    volumes:
      - .:/app

  pgsql:
    image: pgvector/pgvector:pg15
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgressu
      - POSTGRES_PASSWORD=mosdumps123
    ports:
      - "5432:5432"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
#  webserve-django:
#  webserve-static:
  pgdata:
  redisdata: