version: '3'

services:
  web:
    build: .
    image: flexindex.azurecr.io/web
    working_dir: /app/webserve
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  worker:
    build: .
    image: flexindex.azurecr.io/worker
    working_dir: /app/webserve
    command: python manage.py rqworker
    volumes:
      - .:/app
