version: '3'

services:
  web:
    build: .
    image: flexindex.azurecr.io/web
    working_dir: /app/webserve
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  worker:
    build: .
    image: flexindex.azurecr.io/worker
    working_dir: /app/webserve
    command: python manage.py rqworker
    volumes:
      - .:/app

  pgsql:
    image: pgvector/pgvector:pg15
    
