# Generated by Django 5.0 on 2023-12-09 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extensionapis', '0004_singleurl_observedlink_rawdoccapture_url_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('content', models.TextField(max_length=10000)),
                ('reasoning', models.TextField(max_length=10000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensionapis.singleurl')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
