# Generated by Django 5.0.1 on 2024-01-22 23:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('quizzes', '0001_initial'), ('quizzes', '0002_alter_simplequiz_id'), ('quizzes', '0003_simplequizresults'), ('quizzes', '0004_simplequiz_status'), ('quizzes', '0005_alter_simplequiz_status')]

    initial = True

    dependencies = [
        ('extensionapis', '0004_singleurl_observedlink_rawdoccapture_url_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('content', models.TextField(max_length=10000)),
                ('reasoning', models.TextField(max_length=10000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensionapis.singleurl')),
                ('status', models.CharField(choices=[('notstarted', 'NotStarted'), ('building', 'Building'), ('completed', 'Completed'), ('error', 'Error')], default='notstarted', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleQuizResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('results', models.TextField(max_length=64)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.simplequiz')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
