# Generated by Django 5.0 on 2023-12-18 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_simplequiz_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleQuizResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('results', models.TextField(max_length=64)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.simplequiz')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
