# Generated by Django 5.0 on 2024-01-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_simplequizresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplequiz',
            name='status',
            field=models.CharField(choices=[('notstarted', 'NotStarted'), ('building', 'Building'), ('completed', 'Completed'), ('error', 'Error')], default='completed', max_length=16),
        ),
    ]
