# Generated by Django 5.0 on 2024-01-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_simplequiz_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplequiz',
            name='status',
            field=models.CharField(choices=[('notstarted', 'NotStarted'), ('building', 'Building'), ('completed', 'Completed'), ('error', 'Error')], default='notstarted', max_length=16),
        ),
    ]
