# Generated by Django 5.0.4 on 2024-04-30 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customermodels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertableentry',
            name='raw_entries',
        ),
        migrations.RemoveField(
            model_name='usertableentry',
            name='table',
        ),
        migrations.CreateModel(
            name='RawDocumentExtract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('source_table', models.CharField(max_length=64)),
                ('source_pk', models.UUIDField()),
                ('extracted_content', models.JSONField()),
                ('extraction_status', models.CharField(choices=[('inprogress', 'inprogress'), ('done', 'done'), ('error', 'error')])),
                ('extraction_model_details', models.JSONField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'date_modified',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='RawUserTableEntry',
        ),
        migrations.DeleteModel(
            name='UserTableEntry',
        ),
    ]
