# Generated by Django 5.0.4 on 2024-05-03 20:28

from django.db import migrations, models
from uuid import UUID

class Migration(migrations.Migration):

    dependencies = [
        ('customermodels', '0002_remove_usertableentry_raw_entries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdocumentextract',
            name='extraction_pk',
            field=models.UUIDField(default=UUID('8a213033-86ca-4350-a430-9bfaac85351d')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawdocumentextract',
            name='extraction_target',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
