# Generated by Django 5.0.2 on 2024-03-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_looseusersettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="looseusersettings",
            options={"get_latest_by": "date_modified"},
        ),
        migrations.AlterModelOptions(
            name="userkeys",
            options={"get_latest_by": "date_modified"},
        ),
        migrations.AlterModelOptions(
            name="usersubscriptions",
            options={"get_latest_by": "date_modified"},
        ),
        migrations.AlterField(
            model_name="usersubscriptions",
            name="subscription",
            field=models.CharField(
                choices=[("free", "free"), ("monthly_quiz", "monthly_quiz")],
                max_length=32,
            ),
        ),
    ]
