# Generated by Django 5.0.6 on 2024-07-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_date_joined"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="looseusersettings",
            options={},
        ),
        migrations.AddConstraint(
            model_name="looseusersettings",
            constraint=models.UniqueConstraint(
                fields=("user", "key", "value"), name="unique_user_key_value"
            ),
        ),
    ]
