# Generated by Django 5.0.2 on 2024-02-28 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripehandler", "0002_stripeerrorlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeSubscription",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "stripe_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stripehandler.stripeuser",
                    ),
                ),
            ],
        ),
    ]
