# Generated by Django 5.0.2 on 2024-02-17 23:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentCluster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "document_role",
                    models.CharField(
                        choices=[
                            ("rfp", "RFP"),
                            ("proposal", "Proposal"),
                            ("resume", "Resume"),
                            ("verbatim", "Verbatim Templates"),
                            ("intelligence", "Customer Intelligence"),
                            ("unknown", "None"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentExtract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("location_container", models.CharField(max_length=64)),
                ("location_path", models.CharField(max_length=256)),
                (
                    "structure",
                    models.CharField(
                        choices=[
                            ("rawtext", "rawtext"),
                            ("html", "html"),
                            ("sectionsv1", "sectionsv1"),
                        ],
                        max_length=64,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "file_role",
                    models.CharField(
                        choices=[("primary", "Primary"), ("unknown", "None")],
                        max_length=16,
                    ),
                ),
                (
                    "doc_format",
                    models.CharField(
                        choices=[("pdf", "pdf"), ("docx", "docx"), ("zip", "zip")],
                        max_length=8,
                    ),
                ),
                ("doc_name", models.TextField()),
                ("location_container", models.CharField(max_length=64)),
                ("location_path", models.CharField(max_length=256)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("notstarted", "notstarted"),
                            ("done", "done"),
                            ("active", "active"),
                            ("error", "error"),
                        ],
                        max_length=16,
                    ),
                ),
                ("last_jobid", models.CharField(default="", max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RawUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "pdf"), ("docx", "docx"), ("zip", "zip")],
                        max_length=8,
                    ),
                ),
                ("location_container", models.CharField(max_length=64)),
                ("location_path", models.CharField(max_length=256)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
