# Generated by Django 5.0.2 on 2024-02-17 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('privateuploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcluster',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privateuploads.documentcluster'),
        ),
        migrations.AddField(
            model_name='documentextract',
            name='docfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privateuploads.documentfile'),
        ),
        migrations.AddField(
            model_name='rawupload',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privateuploads.documentcluster'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privateuploads.rawupload'),
        ),
    ]
