# Generated by Django 5.0.2 on 2024-03-12 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("privateuploads", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentcluster",
            options={"get_latest_by": "date_modified"},
        ),
        migrations.AlterModelOptions(
            name="documentextract",
            options={"get_latest_by": "date_modified"},
        ),
        migrations.AlterModelOptions(
            name="documentfile",
            options={"get_latest_by": "date_modified"},
        ),
        migrations.AlterModelOptions(
            name="rawupload",
            options={"get_latest_by": "date_modified"},
        ),
    ]
