# Generated by Django 4.2.6 on 2023-10-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("privateuploads", "0002_alter_documentfile_file_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentcluster",
            name="upload_source",
        ),
        migrations.AddField(
            model_name="documentcluster",
            name="document_role",
            field=models.CharField(
                choices=[
                    ("rfp", "RFP"),
                    ("proposal", "Proposal"),
                    ("resume", "Resume"),
                    ("verbatim", "Verbatim Templates"),
                    ("intelligence", "Customer Intelligence"),
                    ("unknown", "None"),
                ],
                default="rfp",
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="file_role",
            field=models.CharField(
                choices=[("rfp", "RFP"), ("unknown", "None")], max_length=16
            ),
        ),
    ]
