# Generated by Django 4.2.6 on 2023-10-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("privateuploads", "0003_remove_documentcluster_upload_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfile",
            name="file_role",
            field=models.CharField(
                choices=[("primary", "Primary"), ("unknown", "None")], max_length=16
            ),
        ),
    ]
