# Generated by Django 4.2.6 on 2023-11-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("privateuploads", "0004_alter_documentfile_file_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfile",
            name="last_jobid",
            field=models.CharField(default="", max_length=128),
        ),
    ]
