# Generated by Django 5.0.2 on 2024-02-17 23:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("share_link", models.CharField(max_length=512)),
                ("name", models.CharField(max_length=512)),
                ("feedback", models.TextField(max_length=2048)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShareRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("shared_object", models.CharField(max_length=128)),
                ("shared_pk", models.IntegerField()),
                ("share_link", models.CharField(max_length=512)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
