# Generated by Django 4.2.6 on 2023-11-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mltrack", "0002_promptresponse_completion_tokens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptresponse",
            name="model_name",
            field=models.TextField(default="aoai"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="promptresponse",
            name="model_service",
            field=models.TextField(default="gpt4-32k"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="promptresponse",
            name="output_role",
            field=models.CharField(
                choices=[
                    ("longsummary", "longsummary"),
                    ("shortsummary", "shortsummary"),
                    ("req_details", "req_details"),
                    ("specific_dates", "specific_dates"),
                    ("legal_notes", "legal_notes"),
                    ("certifications", "certifications"),
                    ("expertise", "expertise"),
                    ("vendors", "vendors"),
                    ("suggested_questions", "suggested_questions"),
                    ("peoplesummary", "peoplesummary"),
                    ("proposalquestions", "proposalquestions"),
                ],
                max_length=64,
            ),
        ),
    ]
