# Generated by Django 5.0.2 on 2024-02-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mltrack", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlevelvectorindex",
            name="chunk_index",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
