# Generated by Django 4.2.7 on 2023-11-17 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("privateuploads", "0005_alter_documentfile_last_jobid"),
        ("mltrack", "0003_promptresponse_model_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractedFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("fact_contents", models.TextField()),
                (
                    "output_role",
                    models.CharField(
                        choices=[
                            ("longsummary", "longsummary"),
                            ("shortsummary", "shortsummary"),
                            ("req_details", "req_details"),
                            ("specific_dates", "specific_dates"),
                            ("legal_notes", "legal_notes"),
                            ("certifications", "certifications"),
                            ("expertise", "expertise"),
                            ("vendors", "vendors"),
                            ("suggested_questions", "suggested_questions"),
                            ("peoplesummary", "peoplesummary"),
                            ("proposalquestions", "proposalquestions"),
                        ],
                        max_length=64,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "doc_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="privateuploads.documentcluster",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
