# Generated by Django 5.0.2 on 2024-02-18 22:41

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mltrack", "0003_userlevelvectorindex_chunk_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlevelvectorindex",
            name="embedding",
            field=pgvector.django.VectorField(dimensions=384),
        ),
    ]
