# Generated by Django 5.0.2 on 2024-02-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mltrack', '0004_alter_userlevelvectorindex_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlevelvectorindex',
            name='embedding_type',
            field=models.CharField(max_length=64),
        ),
    ]
