# Generated by Django 4.2.7 on 2023-11-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mltrack", "0004_extractedfact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractedfact",
            name="output_role",
            field=models.CharField(
                choices=[
                    ("longsummary", "longsummary"),
                    ("shortsummary", "shortsummary"),
                    ("req_details", "req_details"),
                    ("specific_dates", "specific_dates"),
                    ("legal_notes", "legal_notes"),
                    ("certifications", "certifications"),
                    ("expertise", "expertise"),
                    ("vendors", "vendors"),
                    ("suggested_questions", "suggested_questions"),
                    ("peoplesummary", "peoplesummary"),
                    ("proposalquestions", "proposalquestions"),
                    ("tocextract", "tocextract"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="promptresponse",
            name="output_role",
            field=models.CharField(
                choices=[
                    ("longsummary", "longsummary"),
                    ("shortsummary", "shortsummary"),
                    ("req_details", "req_details"),
                    ("specific_dates", "specific_dates"),
                    ("legal_notes", "legal_notes"),
                    ("certifications", "certifications"),
                    ("expertise", "expertise"),
                    ("vendors", "vendors"),
                    ("suggested_questions", "suggested_questions"),
                    ("peoplesummary", "peoplesummary"),
                    ("proposalquestions", "proposalquestions"),
                    ("tocextract", "tocextract"),
                ],
                max_length=64,
            ),
        ),
    ]
