# Generated by Django 5.0.2 on 2024-03-12 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mltrack", "0005_alter_userlevelvectorindex_embedding_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extractedfact",
            options={"get_latest_by": "date_modified"},
        ),
        migrations.AlterModelOptions(
            name="promptresponse",
            options={"get_latest_by": "date_modified"},
        ),
    ]
