# Generated by Django 5.0.1 on 2024-02-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mltrack', '0006_consumerprompttrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerprompttrack',
            name='source_id',
            field=models.CharField(max_length=48),
        ),
    ]
