# Generated by Django 5.0.2 on 2024-02-13 17:41

from pgvector.django import VectorExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mltrack', '0007_alter_consumerprompttrack_source_id'),
    ]

    operations = [
        VectorExtension()
    ]
