# Generated by Django 5.0.6 on 2024-06-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mltrack', '0007_userleveldocvectorindex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtractedFact',
        ),
        migrations.DeleteModel(
            name='PromptResponse',
        ),
    ]
