# Generated by Django 5.0.2 on 2024-02-13 19:01

import django.db.models.deletion
import pgvector.django
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mltrack', '0008_auto_20240213_1741'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevelVectorIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('doc_id', models.UUIDField()),
                ('doc_url', models.CharField(max_length=2024)),
                ('doc_chunk', models.TextField()),
                ('doc_chunk_type', models.CharField(max_length=32)),
                ('embedding', pgvector.django.VectorField(dimensions=1024)),
                ('embedding_type', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
