#name: pre-commit
#
#on:
#  pull_request:
#  push:
##    branches: [main]
#
#jobs:
#  pre-commit:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - uses: actions/setup-python@v5
#      with:
#        python-version: '3.11'
#    - uses: pre-commit/action@v3.0.1



name: pre-commit

on: [push, pull_request]
jobs:
  pre_commit:
    name: Pre-Commit checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch only the latest commit
        ref: ${{ github.event.ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        pip: true

    # Install pre-commit and the configured hooks
    - name: Install pre-commit
      uses: pre-commit/action@v3.0.1
      with:
        install-hook: local
        hookid: "^.*"

    # Get the list of changed files
    - name: Get changed files
      id: get_changed_files
      run: |
        echo "::set-output name=changed_files::$(git diff --name-only --diff-filter=d HEAD^ HEAD)"

    # Run pre-commit checks on the changed files only
    - name: Pre-Commit check
      env:
        CHANGED_FILES: ${{ steps.get_changed_files.outputs.changed_files }}
      run: |
        echo "::set-output name=changed_files::$(git diff --name-only --diff-filter=d HEAD^HEAD)"
        local changed_files=$(echo "${{ env.CHANGED_FILES }}" | tr '\n' ' ')
        pre-commit run --show-diff-on-failure --files="$changed_files"