name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        run: |
          echo "::set-output name=changed_files::$(git diff --name-only --diff-filter=d HEAD^ HEAD)"
          local changed_files=$(echo "${{ env.CHANGED_FILES }}" | tr '\n' ' ')
          ruff --files="$changed_files"